### ISSUE TITLE
string literal in e query and quotes vs apos

### ISSUE THREAD

**Issue by ainthek** [gkz/grasp#45]
grasp -e '__.set(__,"title",__)' -- UI
grasp -e "__.set(__,'title',__)" -- UI

do I need to write this ? to is there some better way to specify literal in e query not sensitive to quoting style ?

**Comment by dfcreative** [comment]
+1

**Comment by gkz** [comment]
Fixed https://github.com/gkz/grasp-equery/commit/d7c5c62a15fdeb7a3390f9b7f5161dfe9fc815aa

installing grasp again will automatically get the new version

**Comment by dfcreative** [comment]
Great!
