### ISSUE TITLE
use function to replace

### ISSUE THREAD

**Issue by JA44** [gkz/grasp#48]
From this ticket, https://github.com/gkz/grasp/issues/22 , we can use a function to replace.

I try this and it doesn't work.

```
 var code = grasp.replace('equery' , 'require($str)' , function( $str ){
                return path.join( __dirname , $str ) + '.js'
            }, '... require("./a/b") ...')
```

I have this error.
```
Option 'replace': Invalid type for 'function ( $str ){
                return path.join( __dirname , $str ) + '.js'
            }' - expected type 'replacement::String'.
```

How can i use this options?

**Comment by dfcreative** [comment]
+1.
It seems to be a trivial but a very useful feature to do.
I’m writing a browserify-transform [graspify](https://github.com/dfcreative/graspify), and there are a bunch of use-cases where passing function to `replace` comes handy. For example, if you need to make some calculations based on matched result.
Besides, having an API conforming with `String.replace` is a very good idea.

@gkz any thoughts?

**Comment by dfcreative** [comment]
@gkz Seems you just have to bump package version:
```
$ npm version minor
$ npm publish
```

**Comment by gkz** [comment]
grasp 0.3.0 released

**Comment by dfcreative** [comment]
Great!
