### ISSUE TITLE
jsx support

### ISSUE THREAD

**Issue by arypurnomoz** [gkz/grasp#53]
is there any plan for using grasp with jsx?

**Comment by gkz** [comment]
Once our parser supports it, it shouldn't be a problem.

**Comment by vasco3** [comment]
Was this fixed with #91 ? 
I tried running `grasp -p "(acorn, {locations: true, ecmaVersion: 6, sourceType: 'module', allowHashBang: true, jsx: true})" if ./index.js` but still complains about an unexpected token when it sees jsx

**Comment by jslz** [comment]
This would be a great feature, now in the world of React and React Native. There are supposedly plugins / early support already for JSX in Acorn and Esprima, how robust I dunno. But gosh I super dream of that working :-)

**Comment by gkz** [comment]
The latest version should support JSX
