### ISSUE TITLE
object props

### ISSUE THREAD

**Issue by nishiviu** [gkz/grasp#60]
Hi George,

could you please help me to find a way to achieve something like this: 

grasp -e 'var x = {};x.y = a;' myJs.js.

Thank you very much.

**Comment by thereforeiam** [comment]
Not quite sure what you are trying to achieve here...
`$ grasp assign[left=member[obj=#x]]`
Could you be more specific ?

**Comment by nishiviu** [comment]
I'm looking for var-dec followed by an assign.

**Comment by gkz** [comment]
variation on `var-decs + exp-statement[exp=assign]`? You can change the subject to the variable declaration by appending a `!`, eg. `var-decs!`

check out http://www.graspjs.com/docs/squery/

**Comment by nishiviu** [comment]
Thank you. 
And please, how would you write a grasp query for an object with some property "a" but without property "b"? I'm trying but can't find a nice simple way of doing it.
