### ISSUE TITLE
Retrieving the file path, line number of a match

### ISSUE THREAD

**Issue by tecfu** [gkz/grasp#61]
I don't see how to retrieve the file path and line number of query matches in the documentation, but I find it hard to believe that this cannot be done with <b>grasp</b>.

How would one go about searching for a function call, getting the filename and line number of each call, and then assigning the file name and line number of the match to an object literal that is passed as an argument to the match?

Let's say I'm searching for: 

```
car.run(__)
```

And I want to pass the file path and line number of each match to its argument (an object). Like so:

```
car.run({
  _filename : ???,
  _line : ???
})
```

**Comment by gkz** [comment]
I think you can do so while using Grasp as a library - check out 
http://www.graspjs.com/docs/lib/#replace

You can get the line by accessing the `node` argument, with `node.loc` which is an object containing the location information.
You will have the filename as you will have read the file and sent the text to Grasp.

**Comment by tecfu** [comment]
That's awesome! Also, thank you for the speedy response.

Going with the previous example, let's say I have the code below.
```
car.run().stop().wash();
```

Now with the following grasper I can get to the line I want. However, I'm not clear how to inject an object into run, or modify existing ones.

I'm sure this is trivial - in [falafel](https://github.com/substack/node-falafel/blob/master/readme.markdown) it would look like:

```
node.update('car.run({...})');
```

But in grasp I can't seem to select/replace the object expression with a query? 
I thought it would be someting like: 

```
var replacer = grasp.replace('equery','car.run(_$params)',function(getRaw,node,query){
	grasp.replace('_$params:someProp','newval');
}, code);
var processedCode = replacer(code);
```

But that obviously doesn't work.

**Comment by gkz** [comment]
When you define the callback used by `grasp.replace`, the third argument, you return a string with the new code that you want to use. You can read more about it in the documentation at: http://www.graspjs.com/docs/lib/#replace
