### ISSUE TITLE
Find some object property and exclude some other one 

### ISSUE THREAD

**Issue by nishiviu** [gkz/grasp#65]
Hi,
 I would like to ask for some help. I need a grasp query for an object with some property "a" but without property "b". 
The following query doesn't look right, there must be a better way, but I couldn't find it yet.
grasp '(obj! prop[key=#constructor][val=func-exp]):not(obj! > prop[key.value=-chains-])' . -r
Thanks.

**Comment by gkz** [comment]
Maybe
```
grasp 'obj! prop[key=#a]:not(prop[key=#a]!~prop[key=#b])'
```

**Comment by nishiviu** [comment]
Thank you!
