### ISSUE TITLE
Cryptic error message when code is empty string

### ISSUE THREAD

**Issue by beyondcompute** [gkz/grasp#67]
Hello. When using Grasp as library. I call `grasp.replace('equery'...` with empty string `''` as "code" and I get:
```
Error: stdin not defined.
```
printed in my console. The error message does not provide clear description of the problem. And I'm not sure if it is a problem in that context anyway. :blush: 

_P.S._ Thank you very much for your job. Grasp is an amazing product! Have a great day!

**Comment by gkz** [comment]
This issue should have been fixed in 0.3.0

see #51
