### ISSUE TITLE
ES6

### ISSUE THREAD

**Issue by OliverJAsh** [gkz/grasp#71]
Acorn now supports ES6, AFAICS.

https://github.com/marijnh/acorn/pull/110

Can we update Grasp to use this?

**Comment by lo1tuma** [comment]
That would be really nice.

**Comment by grsabreu** [comment]
Really need ES6 support

**Comment by elektronik2k5** [comment]
+1

**Comment by gkz** [comment]
Can everyone who commented here install:

    npm install grasp@beta

and test out ES6 support?

thanks!

**Comment by lo1tuma** [comment]
I’ve tried it with a couple of search queries, so far it works quite good. Nice work :+1:.
Is there also an possibility to add additional acorn plugins, so grasp doesn’t fail while parsing JSX syntax?

**Comment by grsabreu** [comment]
Thanks, I'll test it!

**Comment by aquach** [comment]
+1 to Acorn plugins for JSX :)

**Comment by gkz** [comment]
0.4.0 has been released with ES6 support
http://www.graspjs.com/blog/2015/12/29/grasp-0.4.0-released-with-es6-support/
You can attempt to use the `parser` option to get JSX suport

**Comment by aquach** [comment]
Cheers!

**Comment by grsabreu** [comment]
Great!
