### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by belusky** [gkz/grasp#77]
If we are grasping too much files recursive in dir "Maximum call stack" is raised

	$ grasp -e 'if($x){$x()}' -r large-dir/
	Error: Could not parse JavaScript from 'large-dir/a/c/View.js'. Maximum call stack size exceeded
	Error: Could not parse JavaScript from 'large-dir/a/d/View6.js'. Maximum call stack size exceeded
	Error: Could not parse JavaScript from 'large-dir/a/f/View4.js'. Maximum call stack size exceeded
	Maximum call stack size exceeded
	Error: Could not parse JavaScript from 'large-dir/a/k/View2.js'. Maximum call stack size exceeded
	Maximum call stack size exceeded
	Maximum call stack size exceeded
	Maximum call stack size exceeded
	Maximum call stack size exceeded
	Maximum call stack size exceeded

If we are grasping only sub-tree, everythink is OK.

	$ grasp -e 'if($x){$x()}' -r large-dir/a/c/

Not query dependent

**Comment by ainthek** [comment]
+ please fix
