### ISSUE TITLE
exclude files and folder matching certain pattern

### ISSUE THREAD

**Issue by ainthek** [gkz/grasp#97]
Please would it be possible to add some way to exclude files and folders (globbing).
in the API as well on CLI please

**Comment by gkz** [comment]
Can you give an example use case?

**Comment by ainthek** [comment]
Sure: codereviews often I need to exclude test folders, or special files

grasp -s "" -r . --exclude="**/test/**" --exclude="**/tests/**" --exclude "**/*.profile.js",

now I have only two options, build a list of included folders (extra work and limitation of args length) or to grasp ... | grep -v "/test/" after processing, on large repo this is annoying and takes ages.. 

Thanx for help
